### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by sashazykov** [sashazykov/json-repair-rb#1]
Add a `json-repair` command-line binary so the gem can be used from the shell, mirroring upstream `josdejong/jsonrepair`'s CLI.

## Usage

```
json-repair [filename] [options]

  -o, --output FILE  Write repaired JSON to FILE
      --overwrite    Replace the input file in place (requires filename;
                     mutually exclusive with --output)
  -v, --version      Print version and exit
  -h, --help         Print help and exit
```

Behavior:
- No filename → read from stdin, write to stdout.
- With filename → read from file, write to stdout (or `--output` / `--overwrite`).
- `--overwrite` writes to a temp file alongside the input, then renames over the original.
- Repair errors exit non-zero with the error on stderr.

## Examples

```
$ cat broken.json | json-repair
$ json-repair broken.json
$ json-repair broken.json -o fixed.json
$ json-repair broken.json --overwrite
$ echo '{a:1,}' | json-repair
{"a":1}
```

## Tasks

- [ ] Add `exe/json-repair` (already wired via `spec.bindir = 'exe'` in gemspec).
- [ ] Use stdlib `OptionParser` — no new dependencies.
- [ ] Specs covering stdin, file input, `-o`, `--overwrite`, `-v`, `-h`, and error exit code.
- [ ] README section documenting CLI usage.

Skipping upstream's `--buffer` flag (no streaming parser in this gem).
